### ISSUE TITLE
qsslcaudit cannot fetch certificate from servers running on custom ports

### ISSUE THREAD

**Issue by QKaiser** [gremwell/qsslcaudit#14]
I'd like to get qsslcaudit to fetch a certificate from a remote server which is not running on port TCP/443.

I think this is the problematic line: 

https://github.com/gremwell/qsslcaudit/blob/018dc0a88a8c7580f41a7f9b89c991906182a466/src/libqsslcaudit/sslusersettings.cpp#L78

Would be nice to be able to provide the option like this `--server 127.0.0.1:8900` instead of `--server https://127.0.0.1`.

**Comment by zOrg1331** [comment]
The line you referenced sets the default port to `443` if the one was not provided. Currently, it is already possible to set `server` as: `https://127.0.0.1`, `https://127.0.0.1:443`, `127.0.0.1:443` -- they are all equal. Yes, you already able to set `server` as `127.0.0.1:8900`.

However, when checking this I spotted that `qsslcaudit` verifies the validity of remote system certificates. Which, I believe, is a rare case during security tests. So I pushed the new `0.6.1` release fixing this issue.
